apiVersion: v1
kind: ConfigMap
metadata:
  name: script
data:
  script.sh: |
    #!/bin/bash
    echo "Este es un script ejecutado tras una actualización de Helm."
    echo "Aquí puedes añadir el código que necesites ejecutar."
